// ============================================================
// Seed Script — Qué Xu#$4!! Pack Inicial (es-419)
// ============================================================

import { db } from "./index";
import { collections, blackCards, whiteCards } from "./schema";
import { eq } from "drizzle-orm";

const DEFAULT_COLLECTION_ID = "default-pack-inicial";

async function seed() {
  // Check if default collection already exists
  const existing = await db.query.collections.findFirst({
    where: eq(collections.id, DEFAULT_COLLECTION_ID),
  });

  if (existing) {
    console.log("✅ Default collection already exists, skipping seed.");
    return;
  }

  const now = new Date();

  // --- Create the collection ---
  await db.insert(collections).values({
    id: DEFAULT_COLLECTION_ID,
    name: "Qué Xu#$4!! Pack Inicial",
    description: "El pack original con las cartas más irreverentes de Latinoamérica.",
    locale: "es-419",
    isDefault: true,
    createdBy: null,
    createdAt: now,
    updatedAt: now,
  });

  // --- Black Cards (prompts) ---
  // ~15% are Pick 2
  const blackCardTexts: { text: string; pick: number }[] = [
    // Pick 1
    { text: "Lo peor de una fiesta es cuando _____.", pick: 1 },
    { text: "Mi mamá me descubrió _____.", pick: 1 },
    { text: "En mi última peda terminé _____.", pick: 1 },
    { text: "Lo que realmente pasa en los quinceaños: _____.", pick: 1 },
    { text: "El secreto del éxito en la vida es _____.", pick: 1 },
    { text: "Mi abuela siempre decía que _____ era la solución a todo.", pick: 1 },
    { text: "Según mi tío borracho, la clave de la felicidad es _____.", pick: 1 },
    { text: "Lo último que quieres ver al abrir el refri a las 3am: _____.", pick: 1 },
    { text: "Si la chancla pudiera hablar, diría _____.", pick: 1 },
    { text: "El reggaetón más exitoso del año se llama: _____.", pick: 1 },
    { text: "En la reunión familiar nadie esperaba _____.", pick: 1 },
    { text: "Mi crush me dejó de hablar por _____.", pick: 1 },
    { text: "Lo que encontraron debajo de mi cama: _____.", pick: 1 },
    { text: "El verdadero motivo del divorcio fue _____.", pick: 1 },
    { text: "Lo que no te enseñan en la escuela: _____.", pick: 1 },
    { text: "Si pudiera meterle algo al agua de la oficina sería _____.", pick: 1 },
    { text: "La peor excusa para no ir a trabajar: _____.", pick: 1 },
    { text: "Cuando muera, quiero que pongan _____ en mi lápida.", pick: 1 },
    { text: "Dios creó el mundo en 6 días, y el séptimo creó _____.", pick: 1 },
    { text: "El próximo presidente promete eliminar _____.", pick: 1 },
    { text: "Mi ex se describe en una palabra: _____.", pick: 1 },
    { text: "Lo peor que puedes gritar en una iglesia: _____.", pick: 1 },
    { text: "Netflix debería hacer un documental sobre _____.", pick: 1 },
    { text: "El ingrediente secreto de las enchiladas de mi mamá: _____.", pick: 1 },
    { text: "Lo más incómodo de ir al doctor: _____.", pick: 1 },
    { text: "¿Qué hay en el Área 51? _____.", pick: 1 },
    { text: "Antes de morir, todos deberían experimentar _____.", pick: 1 },
    { text: "La nueva materia obligatoria en las escuelas: _____.", pick: 1 },
    { text: "En mi pueblo se hicieron famosos por _____.", pick: 1 },
    { text: "Lo que realmente quiero de Navidad: _____.", pick: 1 },
    { text: "El peor regalo de cumpleaños: _____.", pick: 1 },
    { text: "Si mi perro pudiera hablar, contaría que me vio _____.", pick: 1 },
    { text: "Lo que mi vecino hace a las 2am: _____.", pick: 1 },
    { text: "Cuando digo que estudio, en realidad estoy _____.", pick: 1 },
    { text: "La verdadera razón por la que se hundió el Titanic: _____.", pick: 1 },
    { text: "El emoji que mejor me representa: _____.", pick: 1 },
    { text: "Lo que en verdad piensan los meseros: _____.", pick: 1 },
    { text: "El trend más peligroso de TikTok: _____.", pick: 1 },
    { text: "Mi terapeuta renunció después de escuchar _____.", pick: 1 },
    { text: "El mejor consejo que me dio un taxista: _____.", pick: 1 },
    { text: "Lo que guardan los narcos en sus búnkers: _____.", pick: 1 },
    { text: "Mi talento oculto es _____.", pick: 1 },
    { text: "La peor forma de terminar una relación: _____.", pick: 1 },
    // Pick 2
    { text: "En la prepa me conocían como _____ porque _____.", pick: 2 },
    { text: "Paso 1: _____. Paso 2: _____. Paso 3: Ir a prisión.", pick: 2 },
    { text: "La combinación perfecta: _____ con _____.", pick: 2 },
    { text: "Mi mamá me dio _____ y yo lo cambié por _____.", pick: 2 },
    { text: "_____ es como _____ pero más triste.", pick: 2 },
    { text: "Querido diario, hoy descubrí que _____ y _____ no se mezclan.", pick: 2 },
    { text: "La nueva telenovela se llama '_____ de mi _____'.", pick: 2 },
    { text: "Hoy en Caso Cerrado: _____ demanda a _____ por daños emocionales.", pick: 2 },
    { text: "Mi Uber tenía _____ en el asiento y _____ en el espejo.", pick: 2 },
    { text: "Para olvidar a tu ex necesitas _____ y mucho _____.", pick: 2 },
  ];

  // --- White Cards (responses) ---
  const whiteCardTexts: string[] = [
    "El reggaetón de las 3am",
    "Un grupo de WhatsApp sin nombre",
    "La chancla de mi abuela",
    "Un ex tóxico en modo stalker",
    "La última rebanada de pizza",
    "Un meme del Chavo del 8",
    "Llorar en el baño de un Oxxo",
    "Una torta de tamal con atole",
    "El señor de los elotes a medianoche",
    "Daddy Yankee saliendo de su retiro otra vez",
    "La vecina chismosa",
    "Una cruda moral de tres días",
    "El primo que siempre pide prestado",
    "Mandar un nude al grupo equivocado",
    "Un altar de muertos con tu foto",
    "La rosca de Reyes sin muñeco",
    "El amigo que dice 'yo invito' y nunca paga",
    "Un audio de WhatsApp de 7 minutos",
    "El Wi-Fi del vecino",
    "Hacer la tarea con Wikipedia",
    "Un asado sin carne",
    "El perro callejero que te sigue a casa",
    "Lloriquear por atención",
    "Ghostear a alguien después de la primera cita",
    "El 'mañana te pago' eterno",
    "Un corrido tumbado sobre mi vida",
    "La bendición de la abuela antes de salir",
    "Un tatuaje de Bad Bunny",
    "Fingir que trabajas cuando pasa el jefe",
    "El chile que te hace llorar",
    "Una serenata con mariachi a las 4am",
    "Bailar quebradita en una boda",
    "Los tamales de mi suegra",
    "Un quinceañero con tema de narcos",
    "La fila del banco un lunes",
    "El vecino con la música a todo volumen",
    "Una piñata con forma de político",
    "Comer tacos en la calle sin servilleta",
    "El Chapulín Colorado",
    "Un escándalo en la junta de vecinos",
    "La torta ahogada de Guadalajara",
    "Hacer la fila del SAT todo el día",
    "Un sticker de Buenos Días en el grupo familiar",
    "Quedarte dormido en misa",
    "El tipo que lleva guitarra a todas las fiestas",
    "La salsa Valentina",
    "Mandar 'te amo' al jefe por accidente",
    "Un boleto de avión a cualquier parte",
    "La dieta que empieza el lunes",
    "Un postre que parece droga",
    "La piratería de películas",
    "El primo que vende Herbalife",
    "Decir 'provecho' a desconocidos",
    "Tronar los dedos en público",
    "El olor a pan de muerto en octubre",
    "Una telenovela con 200 capítulos",
    "Tu mamá revisando tu celular",
    "La receta secreta de la abuela",
    "El perreo intenso",
    "Un temblor durante el examen",
    "Cobrar la quincena y que ya se acabó",
    "Un mural de Rivera pero con memes",
    "El dólar a 25 pesos",
    "Rezar tres Ave Marías",
    "El tío que da billetes de a 20",
    "Enchiladas suizas a las 2am",
    "Un Uber Pool con 6 personas",
    "La señora que vende quesadillas sin queso",
    "El Chavo en Netflix",
    "Tu ex dando like a tus fotos viejas",
    "Un payaso en una fiesta de adultos",
    "La cruda de domingo",
    "Un albur que nadie entendió",
    "El 'ya merito llego' que son 45 minutos",
    "Pedir perdón con un Starbucks",
    "Un reggaetón cristiano",
    "El agua de Jamaica bien fría",
    "El mosquito que no te deja dormir",
    "Hacerse el muerto para no ir a la escuela",
    "La señora del metro que vende dulces",
    "Un piropo a las 7am",
    "El que trae sandalias con calcetines",
    "Un partido de futbol con tu familia política",
    "Mentir en tu CV",
    "Una bendición de cura borracho",
    "La mordida en tu cumpleaños",
    "Un bebé llorando en un avión",
    "El padrino que desaparece después del bautizo",
    "La frase 'es que en mi rancho...'",
    "Un grupo de mamás de WhatsApp",
    "La chancla voladora",
    "Empezar una conversación con 'no me vas a creer pero...'",
    "Un mezcal de gusano",
    "Ponerle limón y chile a absolutamente todo",
    "El tío que cuenta la misma historia en cada fiesta",
    "Una procesión con fuegos artificiales",
    "Ir a Costco un sábado",
    "La bolsa del mandado de tela",
    "Un plomero que cobra por respirer",
    "El señor de los tamales del domingo",
    "Un exorcismo en vivo por YouTube",
    "La promesa de ir al gym",
    "Un presidente con Twitter a las 6am",
    "La Coca-Cola de vidrio",
    "Un corrido sobre tu vida amorosa",
    "El compadre que siempre está pedo",
    "La sopa de tu mamá cuando estás enfermo",
    "Hacer el ridículo en karaoke",
    "Un funeral con banda sinaloense",
    "El wey que dice 'yo sé de todo'",
    "Una caguama entre amigos",
    "Poner Pedrito Sola como foto de perfil",
    "El maestro que pone película los viernes",
    "Un Volkswagen del 98 tuneado",
    "La frase 'échale ganas'",
    "Un crush que ni sabe que existes",
    "Dormir con ventilador a toda potencia",
    "El cajero que se traba en el peor momento",
    "Un mariachi tocando 'Amor Eterno' a las 5am",
    "Comer en Tupperware en la oficina",
    "El grito de '¡GOOOOL!' de tu vecino",
    "Una cadena de oración por WhatsApp",
    "El primo que va a la prepa a los 30",
    "Un chisme de pasillo",
    "Tomar agua de la llave y sobrevivir",
    "El 'me salió más caro el caldo que las albóndigas'",
    "Un narcotúnel que sale en tu jardín",
    "La playlist de 'Para llorar en el shower'",
    "Un amarre de brujo de Catemaco",
    "La herencia de un terreno en litigio",
    "Quemar las tortillas y culpar al comal",
    "Un viaje a Cancún con todo incluido",
    "El 'yo no fui' de toda la vida",
    "Hacer la fila para votar con huaraches",
    "Un escándalo de corrupción más",
    "El secreto de la receta de mi tía",
    "La foto del PRI en la pared de la abuela",
    "Un Tecate bien fría en la playa",
    "El primo que emigró y habla con acento gringo",
    "Un examen que no estudiaste",
    "Tortillas hechas a mano",
    "El chico que pone estado cada 5 minutos",
    "Un Día de Muertos en el panteón",
    "La eterna promesa de 'ya vamos a mejorar'",
    "Roncar como locomotora",
    "Un vochito color pistache",
    "El complot del agua de horchata",
    "Una selfie con el ataúd",
    "El perro de la cuadra que persigue motos",
    "Un altar con la foto de tu ex",
    "Decir 'ahorita' y tardar tres horas",
    "La cantina de la esquina",
    "Mentir en la declaración de impuestos",
    "Un concierto de Los Ángeles Azules",
    "El pozole de los domingos",
    "Ir a misa solo por las donas de después",
    "Un chiste de Pepito",
    "La tía que te pregunta cuándo te casas",
    "Un chofer de combi con estilo",
    "El elote con mayonesa y chile",
    "Un correo de 'urgente' del jefe a las 11pm",
    "La lotería de la feria",
    "Escapar del país con una maleta de dinero",
    "Un incendio provocado por un cuete",
    "El café de olla de la abuela",
    "Un tinaco con iguanas",
    "La banda de guerra del secundario",
    "Caerse en público y fingir que no pasó nada",
    "El tequila que te cambia la personalidad",
    "Un globo de Cantinflas",
    "La cena de Navidad con 50 familiares",
    "Un tamal de chipilín",
    "El ruido del tianguis a las 6am",
    "Un influencer de Tepito",
    "La 'mordida' del policía",
    "Un pan dulce con chocolate caliente",
    "El truco de poner una moneda en la puerta",
    "Un bautizo con 200 invitados",
    "La cobija de tigre",
    "Un peluche gigante del tianguis",
    "El primo que vende cosas 'originales'",
    "La fila de la tortillería",
    "Un asalto en camión narrado como crónica",
    "El clásico 'luego te lo pago'",
    "Una limpia con huevo y ruda",
    "El taxímetro que sube solo",
    "Un corrido que cuenta tu peor vergüenza",
    "La milanesa de la comida corrida",
    "Un tutorial de YouTube de 45 minutos",
    "El secreto que todos saben pero nadie dice",
    "Una foto con el burro de Tijuana",
    "El arroz rojo de las fiestas",
    "Un sticker del Papá de 'ya llegué hija'",
    "La Rosca de Reyes con 3 muñequitos",
    "Un 'ya valió' colectivo",
    "El olor de gasolina en la mañana",
    "Un ponche de frutas con piquete",
    "La frase 'en mis tiempos'",
    "Una balacera de confeti",
    "El pollo de los domingos",
    "Un michelada perfecta",
    "Ir al tianguis con 50 pesos y volver cargado",
    "La canción de 'Las Mañanitas' desafinada",
    "Un payaso de rodeo en una fiesta infantil",
    "El atole de la esquina",
  ];

  // --- Insert black cards ---
  const blackCardValues = blackCardTexts.map((card) => ({
    id: crypto.randomUUID(),
    collectionId: DEFAULT_COLLECTION_ID,
    text: card.text,
    pick: card.pick,
  }));

  await db.insert(blackCards).values(blackCardValues);

  // --- Insert white cards ---
  const whiteCardValues = whiteCardTexts.map((text) => ({
    id: crypto.randomUUID(),
    collectionId: DEFAULT_COLLECTION_ID,
    text,
  }));

  await db.insert(whiteCards).values(whiteCardValues);

  console.log(`🃏 Seeded "${DEFAULT_COLLECTION_ID}":`);
  console.log(`   ${blackCardValues.length} black cards (${blackCardValues.filter(c => c.pick === 2).length} Pick 2)`);
  console.log(`   ${whiteCardValues.length} white cards`);
}

seed()
  .then(() => {
    console.log("✅ Seed complete!");
    process.exit(0);
  })
  .catch((err) => {
    console.error("❌ Seed failed:", err);
    process.exit(1);
  });
